CREATE TABLE COUNTRY(
 COUNTRY_ID INTEGER PRIMARY KEY,
 COUNTRY_CODE VARCHAR (20) UNIQUE NOT NULL,
 COUNTRY_NAME VARCHAR (50) UNIQUE NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE LOCATION( 
 LOCATION_ID INTEGER UNIQUE NOT NULL,
 LOCATION_CODE VARCHAR (20) UNIQUE NOT NULL,
 LOCATION_NAME VARCHAR (100) UNIQUE NOT NULL,
 COUNTRY_ID INTEGER NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 PRIMARY KEY (LOCATION_ID, COUNTRY_ID),
 CONSTRAINT LOCATION_COUNTRY_ID_FKEY FOREIGN KEY (COUNTRY_ID)
 REFERENCES COUNTRY (COUNTRY_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE LOCATION_BUSINESS_UNIT(
 LOCATION_ID INTEGER NOT NULL,
 BUSINESS_UNIT_ID INTEGER NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL, 
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 CONSTRAINT LOCATION_BUSINESS_UNIT_LOCATION_ID_FKEY FOREIGN KEY (LOCATION_ID)
 REFERENCES LOCATION (LOCATION_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION,
 CONSTRAINT LOCATION_BUSINESS_UNIT_BUSINESS_UNIT_ID_FKEY FOREIGN KEY (BUSINESS_UNIT_ID)
 REFERENCES BUSINESS_UNIT (BUSINESS_UNIT_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE BUSINESS_UNIT(
 BUSINESS_UNIT_ID INTEGER UNIQUE PRIMARY KEY,
 BUSINESS_UNIT_CODE VARCHAR (20) UNIQUE NOT NULL,
 BUSINESS_UNIT_NAME VARCHAR (100) UNIQUE NOT NULL,
 BUSINESS_UNIT_GROUP VARCHAR (100) ,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE BUSINESS_UNIT_KPI_CATEGORY(
 BUSINESS_UNIT_ID INTEGER NOT NULL,
 KPI_CATEGORY_ID INTEGER NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 CONSTRAINT BUSINESS_UNIT_KPI_CATEGORY_BUSINESS_UNIT_ID_FKEY FOREIGN KEY (BUSINESS_UNIT_ID)
 REFERENCES BUSINESS_UNIT (BUSINESS_UNIT_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION,
 CONSTRAINT BUSINESS_UNIT_KPI_CATEGORY_KPI_CATEGORY_ID_FKEY FOREIGN KEY (KPI_CATEGORY_ID)
 REFERENCES KPI_CATEGORY (KPI_CATEGORY_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE KPI_CATEGORY(
 KPI_CATEGORY_ID INTEGER UNIQUE PRIMARY KEY,
 KPI_CATEGORY_CODE VARCHAR (20) UNIQUE NOT NULL,
 KPI_CATEGORY_NAME VARCHAR (100) UNIQUE NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);


CREATE TABLE KPI(
 KPI_ID INTEGER UNIQUE PRIMARY KEY,
 KPI_CODE VARCHAR (100) UNIQUE NOT NULL,
 KPI_CATEGORY_ID INTEGER UNIQUE NOT NULL,
 KPI_NAME VARCHAR (100) UNIQUE NOT NULL,
 KPI_MEASUREMENT_UNIT VARCHAR (100) ,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 CONSTRAINT KPI_KPI_CATEGORY_ID_FKEY FOREIGN KEY (KPI_CATEGORY_ID)
 REFERENCES KPI_CATEGORY (KPI_CATEGORY_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
);


CREATE TABLE KPI_PRODUCTION_LINE(
KPI_ID INTEGER NOT NULL,
 PRODUCTION_LINE_ID INTEGER NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 PRIMARY KEY(KPI_ID, PRODUCTION_LINE_ID),
 CONSTRAINT KPI_PRODUCTION_LINE_KPI_ID_FKEY FOREIGN KEY (KPI_ID)
 REFERENCES KPI (KPI_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION,
 CONSTRAINT KPI_PRODUCTION_LINE_PRODUCTION_LINE_ID_FKEY FOREIGN KEY (PRODUCTION_LINE_ID)
 REFERENCES PRODUCTION_LINE (PRODUCTION_LINE_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
 );
 
 
CREATE TABLE PRODUCTION_LINE(
 PRODUCTION_LINE_ID INTEGER UNIQUE PRIMARY KEY,
 PRODUCTION_LINE_CODE VARCHAR (20) UNIQUE NOT NULL,
 PRODUCTION_LINE_NAME VARCHAR (100) UNIQUE NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE KPI_DATA(
KPI_DATA_ID INTEGER UNIQUE PRIMARY KEY,
 LOCATION_ID INTEGER NOT NULL,
 KPI_ID INTEGER NOT NULL,
 BUSINESS_UNIT_ID INTEGER NOT NULL,
 PRODUCTION_LINE_ID INTEGER NOT NULL,
 VALUE DECIMAL(20,4) DEFAULT 0,
 KPI_DATE TIMESTAMP NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE PRODUCTION_LINE_SET(
 SET_ID INTEGER UNIQUE NOT NULL,
 SET_CODE VARCHAR (20) UNIQUE NOT NULL,
 SET_NAME VARCHAR (20) UNIQUE NOT NULL,
 BUSINESS_UNIT_ID INTEGER NOT NULL,
 LOCATION_ID INTEGER NOT NULL,
 KPI_CATEGORY_ID INTEGER NOT NULL,
 KPI_ID INTEGER NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 CONSTRAINT PRODUCTION_LINE_SET_BUSINESS_UNIT_ID_FKEY FOREIGN KEY (BUSINESS_UNIT_ID)
 REFERENCES BUSINESS_UNIT (BUSINESS_UNIT_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION,
 CONSTRAINT PRODUCTION_LINE_SET_LOCATION_ID_FKEY FOREIGN KEY (LOCATION_ID)
 REFERENCES LOCATION (LOCATION_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE PRODUCTION_LINE_SET_DETAIL(
 SET_ID INTEGER NOT NULL ,
 PRODUCTION_LINE_ID INTEGER NOT NULL, 
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 PRIMARY KEY(SET_ID, PRODUCTION_LINE_ID),
 CONSTRAINT PRODUCTION_LINE_SET_DETAIL_SET_ID_FKEY FOREIGN KEY (SET_ID)
 REFERENCES PRODUCTION_LINE_SET (SET_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION,
 CONSTRAINT PRODUCTION_LINE_SET_DETAIL_PRODUCTION_LINE_ID_FKEY FOREIGN KEY (PRODUCTION_LINE_ID)
 REFERENCES PRODUCTION_LINE (PRODUCTION_LINE_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
);


CREATE TABLE ENTITY(
 ENTITY_ID INTEGER UNIQUE PRIMARY KEY,
 ENTITY_CODE VARCHAR (20) UNIQUE NOT NULL,
 ENTITY_NAME VARCHAR (100) UNIQUE NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);


CREATE TABLE BENCHMARK(
 BENCHMARK_ID INTEGER UNIQUE PRIMARY KEY,
 BENCHMARK_CODE VARCHAR (20) UNIQUE NOT NULL,
 BENCHMARK_NAME VARCHAR (20) UNIQUE NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE BENCHMARK_SET_DETAIL(
 BENCHMARK_ID INTEGER UNIQUE PRIMARY KEY,
 SET_ID INTEGER UNIQUE NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY VARCHAR(100)  NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100)  NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,
 CONSTRAINT BENCHMARK_SET_DETAIL_BENCHMARK_ID_FKEY FOREIGN KEY (BENCHMARK_ID)
 REFERENCES BENCHMARK (BENCHMARK_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT BENCHMARK_SET_DETAIL_SET_ID_FKEY FOREIGN KEY (SET_ID)
 REFERENCES PRODUCTION_LINE_SET (SET_ID) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION
);





